import { type Layoff, type InsertLayoff, type User, type InsertUser } from "@shared/schema";
import { randomUUID } from "crypto";

export interface IStorage {
  getLayoffs(): Promise<Layoff[]>;
  getLayoff(id: string): Promise<Layoff | undefined>;
  createLayoff(layoff: InsertLayoff): Promise<Layoff>;
  getUser(id: string): Promise<User | undefined>;
  getUserByUsername(username: string): Promise<User | undefined>;
  createUser(user: InsertUser): Promise<User>;
}

export class MemStorage implements IStorage {
  private layoffs: Map<string, Layoff>;
  private users: Map<string, User>;

  constructor() {
    this.layoffs = new Map();
    this.users = new Map();
    this.seed();
  }

  private seed() {
    const entries: Omit<Layoff, "id">[] = [
      { company: "Block, Inc.", logo: "block", industry: "Fintech", employeesCut: 4000, totalEmployeesBefore: 10000, percentageCut: 40, trigger: "AI-driven structural redesign", layoffType: "2026", stockImpact: "positive", description: "Jack Dorsey restructured Block around AI efficiency, cutting 40% of the workforce in a single massive round. Not financial distress — a deliberate architectural decision that the company can now run leaner with AI doing coordination work.", date: "2026-02-01", ceoQuote: "Future companies run lean and AI-native. Management layers shrink. Coordination jobs disappear first.", sourceUrl: null },
      { company: "Amazon", logo: "amazon", industry: "E-Commerce / Cloud", employeesCut: 27000, totalEmployeesBefore: 1540000, percentageCut: 1.75, trigger: "Over-hiring correction + automation", layoffType: "2022", stockImpact: "positive", description: "Amazon eliminated roles across retail, HR, and devices divisions after aggressive pandemic hiring. Automation of warehouse and logistics roles accelerated the consolidation.", date: "2023-01-20", ceoQuote: null, sourceUrl: null },
      { company: "Microsoft", logo: "microsoft", industry: "Software / Cloud", employeesCut: 10000, totalEmployeesBefore: 221000, percentageCut: 4.5, trigger: "AI restructuring", layoffType: "2026", stockImpact: "positive", description: "Microsoft folded multiple product teams into its AI org, eliminating redundant roles. A company-wide pivot where AI becomes the core delivery layer.", date: "2023-01-18", ceoQuote: null, sourceUrl: null },
      { company: "Google", logo: "google", industry: "Search / AI", employeesCut: 12000, totalEmployeesBefore: 190000, percentageCut: 6.3, trigger: "Efficiency push", layoffType: "2022", stockImpact: "neutral", description: "Google removed middle management layers and consolidated business units under its efficiency mandate.", date: "2023-01-20", ceoQuote: null, sourceUrl: null },
      { company: "Meta Platforms", logo: "meta", industry: "Social Media / AI", employeesCut: 21000, totalEmployeesBefore: 87000, percentageCut: 24, trigger: "Year of efficiency", layoffType: "2022", stockImpact: "positive", description: "Zuckerberg's 'Year of Efficiency' flattened the org chart and removed an entire layer of management.", date: "2023-03-14", ceoQuote: null, sourceUrl: null },
      { company: "Intel", logo: "intel", industry: "Semiconductors", employeesCut: 15000, totalEmployeesBefore: 124800, percentageCut: 15, trigger: "Margin pressure + automation", layoffType: "2008", stockImpact: "negative", description: "Intel faced margin compression from AMD and ARM competition alongside automation reducing manufacturing overhead.", date: "2024-08-01", ceoQuote: null, sourceUrl: null },
      { company: "Salesforce", logo: "salesforce", industry: "CRM / AI", employeesCut: 8000, totalEmployeesBefore: 79000, percentageCut: 10, trigger: "AI-CRM shift", layoffType: "2026", stockImpact: "positive", description: "Salesforce consolidated support and ops roles as AI agents began handling tier-1 customer issues.", date: "2023-01-04", ceoQuote: null, sourceUrl: null },
      { company: "Cisco Systems", logo: "cisco", industry: "Networking", employeesCut: 4250, totalEmployeesBefore: 84900, percentageCut: 5, trigger: "Cloud transition", layoffType: "2022", stockImpact: "neutral", description: "Cisco shifted from hardware-centric revenue to software subscriptions, reducing hardware-adjacent roles.", date: "2024-02-14", ceoQuote: null, sourceUrl: null },
      { company: "Spotify", logo: "spotify", industry: "Audio Streaming", employeesCut: 1500, totalEmployeesBefore: 9800, percentageCut: 15, trigger: "Profitability focus", layoffType: "2022", stockImpact: "positive", description: "Spotify cut podcast and product teams to reach profitability.", date: "2023-12-04", ceoQuote: null, sourceUrl: null },
      { company: "Unity Technologies", logo: "unity", industry: "Game Engine / AI", employeesCut: 1800, totalEmployeesBefore: 7400, percentageCut: 25, trigger: "Business model reset", layoffType: "2022", stockImpact: "negative", description: "Unity restructured after a failed runtime fee policy caused massive developer backlash.", date: "2024-01-08", ceoQuote: null, sourceUrl: null },
      { company: "Tesla, Inc.", logo: "tesla", industry: "EV / Robotics", employeesCut: 14000, totalEmployeesBefore: 140000, percentageCut: 10, trigger: "Manufacturing automation", layoffType: "2026", stockImpact: "neutral", description: "Tesla cut production support and administrative roles as factory automation reduced human headcount per vehicle.", date: "2024-04-15", ceoQuote: null, sourceUrl: null },
      { company: "Twitter / X", logo: null, industry: "Social Media", employeesCut: 6000, totalEmployeesBefore: 7500, percentageCut: 80, trigger: "Ownership restructuring", layoffType: "2022", stockImpact: null, description: "Elon Musk gutted the workforce immediately after acquisition, cutting engineering, trust & safety, and communications.", date: "2022-11-04", ceoQuote: null, sourceUrl: null },
      { company: "Snap Inc.", logo: null, industry: "Social Media", employeesCut: 1300, totalEmployeesBefore: 6400, percentageCut: 20, trigger: "Revenue decline + restructuring", layoffType: "2022", stockImpact: "negative", description: "Snap cut 20% of staff as ad revenue declined amid competition from TikTok and economic downturn.", date: "2022-08-31", ceoQuote: null, sourceUrl: null },
      { company: "Stripe", logo: null, industry: "Fintech", employeesCut: 1120, totalEmployeesBefore: 8000, percentageCut: 14, trigger: "Over-hiring correction", layoffType: "2022", stockImpact: null, description: "Stripe admitted to over-hiring during the pandemic boom and cut 14% of its workforce.", date: "2022-11-03", ceoQuote: null, sourceUrl: null },
      { company: "Shopify", logo: null, industry: "E-Commerce", employeesCut: 1000, totalEmployeesBefore: 10000, percentageCut: 10, trigger: "Over-hiring correction", layoffType: "2022", stockImpact: "negative", description: "CEO Tobi Lutke said he misjudged how long the e-commerce boom would last and took responsibility.", date: "2022-07-26", ceoQuote: null, sourceUrl: null },
      { company: "Lyft", logo: null, industry: "Rideshare", employeesCut: 1072, totalEmployeesBefore: 4800, percentageCut: 22, trigger: "Profitability pressure", layoffType: "2022", stockImpact: "positive", description: "Lyft slashed headcount in the lead-up to profitability targets amid fierce competition with Uber.", date: "2023-04-27", ceoQuote: null, sourceUrl: null },
      { company: "Uber", logo: null, industry: "Rideshare / Delivery", employeesCut: 6700, totalEmployeesBefore: 26900, percentageCut: 25, trigger: "Pandemic + restructuring", layoffType: "2008", stockImpact: "neutral", description: "Uber cut a quarter of its workforce as pandemic lockdowns decimated ride demand.", date: "2020-05-18", ceoQuote: null, sourceUrl: null },
      { company: "Airbnb", logo: null, industry: "Travel / Hospitality", employeesCut: 1900, totalEmployeesBefore: 7500, percentageCut: 25, trigger: "Pandemic revenue collapse", layoffType: "2008", stockImpact: null, description: "Airbnb cut 25% of staff as global travel halted during COVID-19 lockdowns.", date: "2020-05-05", ceoQuote: null, sourceUrl: null },
      { company: "PayPal", logo: null, industry: "Fintech", employeesCut: 2500, totalEmployeesBefore: 30000, percentageCut: 8, trigger: "Efficiency restructuring", layoffType: "2022", stockImpact: "positive", description: "PayPal cut roles to streamline operations and focus on core payments products.", date: "2024-01-30", ceoQuote: null, sourceUrl: null },
      { company: "DocuSign", logo: null, industry: "SaaS", employeesCut: 700, totalEmployeesBefore: 7400, percentageCut: 9, trigger: "Post-pandemic correction", layoffType: "2022", stockImpact: "neutral", description: "DocuSign reduced headcount as pandemic-era digital signing demand normalized.", date: "2023-02-16", ceoQuote: null, sourceUrl: null },
      { company: "Twilio", logo: null, industry: "Communications API", employeesCut: 1500, totalEmployeesBefore: 8600, percentageCut: 17, trigger: "Profitability restructuring", layoffType: "2022", stockImpact: "positive", description: "Twilio cut 17% of staff to reach profitability after years of growth-first strategy.", date: "2023-02-13", ceoQuote: null, sourceUrl: null },
      { company: "Zoom", logo: null, industry: "Video Communications", employeesCut: 1300, totalEmployeesBefore: 8400, percentageCut: 15, trigger: "Post-pandemic normalization", layoffType: "2022", stockImpact: "neutral", description: "Zoom cut 15% of staff as video meeting demand normalized after the pandemic.", date: "2023-02-07", ceoQuote: null, sourceUrl: null },
      { company: "Dell Technologies", logo: null, industry: "Hardware / IT", employeesCut: 13000, totalEmployeesBefore: 133000, percentageCut: 10, trigger: "PC demand decline + AI pivot", layoffType: "2022", stockImpact: "neutral", description: "Dell cut roles as PC demand slowed and the company restructured toward AI infrastructure.", date: "2023-02-06", ceoQuote: null, sourceUrl: null },
      { company: "IBM", logo: null, industry: "Enterprise IT / AI", employeesCut: 3900, totalEmployeesBefore: 280000, percentageCut: 1.4, trigger: "AI automation of HR/admin", layoffType: "2026", stockImpact: "positive", description: "IBM froze hiring for roles AI could replace, particularly in HR and non-customer-facing functions.", date: "2023-01-25", ceoQuote: null, sourceUrl: null },
      { company: "SAP", logo: null, industry: "Enterprise Software", employeesCut: 8000, totalEmployeesBefore: 107000, percentageCut: 7, trigger: "AI restructuring", layoffType: "2026", stockImpact: "positive", description: "SAP restructured around AI, cutting roles that could be automated while hiring AI specialists.", date: "2024-01-23", ceoQuote: null, sourceUrl: null },
      { company: "eBay", logo: null, industry: "E-Commerce", employeesCut: 1000, totalEmployeesBefore: 13000, percentageCut: 8, trigger: "AI efficiency restructuring", layoffType: "2026", stockImpact: "positive", description: "eBay cut roles as AI took over listing optimization, customer support, and search functions.", date: "2024-01-23", ceoQuote: null, sourceUrl: null },
      { company: "Okta", logo: null, industry: "Identity Security", employeesCut: 400, totalEmployeesBefore: 5800, percentageCut: 7, trigger: "Profitability restructuring", layoffType: "2022", stockImpact: "neutral", description: "Okta reduced headcount to improve margins and operational efficiency.", date: "2023-02-01", ceoQuote: null, sourceUrl: null },
      { company: "Wayfair", logo: null, industry: "E-Commerce / Furniture", employeesCut: 1750, totalEmployeesBefore: 15000, percentageCut: 12, trigger: "Post-pandemic correction", layoffType: "2022", stockImpact: "positive", description: "Wayfair reversed pandemic hiring as furniture demand normalized.", date: "2023-01-20", ceoQuote: null, sourceUrl: null },
      { company: "Coinbase", logo: null, industry: "Crypto Exchange", employeesCut: 950, totalEmployeesBefore: 4700, percentageCut: 20, trigger: "Crypto winter", layoffType: "2008", stockImpact: "negative", description: "Coinbase slashed headcount during the crypto downturn as trading volumes collapsed.", date: "2023-01-10", ceoQuote: null, sourceUrl: null },
      { company: "Robinhood", logo: null, industry: "Fintech / Trading", employeesCut: 780, totalEmployeesBefore: 3400, percentageCut: 23, trigger: "Trading volume decline", layoffType: "2008", stockImpact: "negative", description: "Robinhood cut nearly a quarter of staff as meme-stock era trading volumes evaporated.", date: "2022-08-02", ceoQuote: null, sourceUrl: null },
      { company: "Rivian", logo: null, industry: "EV Manufacturing", employeesCut: 840, totalEmployeesBefore: 14000, percentageCut: 6, trigger: "Cost reduction", layoffType: "2008", stockImpact: "negative", description: "Rivian cut roles to preserve cash as EV production costs remained high.", date: "2023-02-01", ceoQuote: null, sourceUrl: null },
      { company: "Lucid Motors", logo: null, industry: "EV Manufacturing", employeesCut: 1300, totalEmployeesBefore: 7000, percentageCut: 18, trigger: "Production scaling issues", layoffType: "2008", stockImpact: "negative", description: "Lucid reduced staff amid production challenges and lower-than-expected demand.", date: "2024-03-01", ceoQuote: null, sourceUrl: null },
      { company: "Palantir", logo: null, industry: "Data Analytics / AI", employeesCut: 250, totalEmployeesBefore: 3700, percentageCut: 7, trigger: "Operational efficiency", layoffType: "2022", stockImpact: "positive", description: "Palantir trimmed roles while pivoting hard to AI platform products.", date: "2023-01-11", ceoQuote: null, sourceUrl: null },
      { company: "Splunk", logo: null, industry: "Data Analytics", employeesCut: 325, totalEmployeesBefore: 7800, percentageCut: 4, trigger: "Profitability focus", layoffType: "2022", stockImpact: "neutral", description: "Splunk cut roles ahead of its acquisition by Cisco to streamline operations.", date: "2023-11-30", ceoQuote: null, sourceUrl: null },
      { company: "Informatica", logo: null, industry: "Data Integration", employeesCut: 450, totalEmployeesBefore: 5700, percentageCut: 8, trigger: "Cloud transition restructuring", layoffType: "2022", stockImpact: "neutral", description: "Informatica reduced headcount while transitioning from on-premise to cloud-native data services.", date: "2023-05-15", ceoQuote: null, sourceUrl: null },
      { company: "VMware", logo: null, industry: "Virtualization / Cloud", employeesCut: 2800, totalEmployeesBefore: 38000, percentageCut: 7, trigger: "Broadcom acquisition restructuring", layoffType: "2022", stockImpact: null, description: "VMware cut roles as Broadcom restructured post-acquisition to eliminate redundancies.", date: "2024-01-15", ceoQuote: null, sourceUrl: null },
      { company: "Qualcomm", logo: null, industry: "Semiconductors / Mobile", employeesCut: 1258, totalEmployeesBefore: 51000, percentageCut: 2.5, trigger: "Mobile slowdown", layoffType: "2022", stockImpact: "neutral", description: "Qualcomm reduced headcount as smartphone sales slowed globally.", date: "2023-03-01", ceoQuote: null, sourceUrl: null },
      { company: "Philips", logo: null, industry: "Health Tech", employeesCut: 6000, totalEmployeesBefore: 79000, percentageCut: 8, trigger: "Recall crisis + restructuring", layoffType: "2008", stockImpact: "negative", description: "Philips cut thousands after a major medical device recall damaged revenue and reputation.", date: "2023-01-30", ceoQuote: null, sourceUrl: null },
      { company: "Ericsson", logo: null, industry: "Telecom Equipment", employeesCut: 8500, totalEmployeesBefore: 105000, percentageCut: 8, trigger: "5G investment slowdown", layoffType: "2008", stockImpact: "negative", description: "Ericsson reduced staff as telecom carriers slowed 5G infrastructure spending.", date: "2023-06-26", ceoQuote: null, sourceUrl: null },
      { company: "Nokia", logo: null, industry: "Telecom Equipment", employeesCut: 14000, totalEmployeesBefore: 86000, percentageCut: 16, trigger: "Telecom downturn", layoffType: "2008", stockImpact: "negative", description: "Nokia announced deep cuts as North American and European telecom operators reduced spending.", date: "2023-10-19", ceoQuote: null, sourceUrl: null },
      { company: "Accenture", logo: null, industry: "Consulting / IT Services", employeesCut: 19000, totalEmployeesBefore: 738000, percentageCut: 2.5, trigger: "AI automation + demand shift", layoffType: "2026", stockImpact: "positive", description: "Accenture restructured as AI tooling automated consulting deliverables and project coordination.", date: "2023-03-23", ceoQuote: null, sourceUrl: null },
      { company: "Roku", logo: null, industry: "Streaming / Hardware", employeesCut: 600, totalEmployeesBefore: 3600, percentageCut: 17, trigger: "Profitability restructuring", layoffType: "2022", stockImpact: "positive", description: "Roku cut 17% of staff as streaming ad revenue growth slowed.", date: "2023-11-15", ceoQuote: null, sourceUrl: null },
      { company: "Sonos", logo: null, industry: "Consumer Electronics", employeesCut: 100, totalEmployeesBefore: 1800, percentageCut: 6, trigger: "App relaunch failure", layoffType: "2022", stockImpact: "negative", description: "Sonos cut roles after a disastrous app redesign caused customer backlash and revenue loss.", date: "2024-08-13", ceoQuote: null, sourceUrl: null },
      { company: "Grammarly", logo: null, industry: "AI Writing", employeesCut: 230, totalEmployeesBefore: 1200, percentageCut: 19, trigger: "AI product pivot", layoffType: "2026", stockImpact: null, description: "Grammarly restructured around its AI assistant product, cutting roles made redundant by its own technology.", date: "2024-11-01", ceoQuote: null, sourceUrl: null },
      { company: "Figma", logo: null, industry: "Design Tools", employeesCut: 50, totalEmployeesBefore: 1200, percentageCut: 4, trigger: "Post-acquisition normalization", layoffType: "2022", stockImpact: null, description: "Figma trimmed roles after the failed Adobe acquisition and refocused on core product.", date: "2024-01-10", ceoQuote: null, sourceUrl: null },
      { company: "Canva", logo: null, industry: "Design / SaaS", employeesCut: 80, totalEmployeesBefore: 4000, percentageCut: 2, trigger: "AI efficiency gains", layoffType: "2026", stockImpact: null, description: "Canva quietly reduced teams as AI features automated design template creation and support.", date: "2025-09-15", ceoQuote: null, sourceUrl: null },
      { company: "Notion", logo: null, industry: "Productivity / AI", employeesCut: 40, totalEmployeesBefore: 700, percentageCut: 6, trigger: "Efficiency restructuring", layoffType: "2022", stockImpact: null, description: "Notion reduced headcount while doubling down on its AI workspace features.", date: "2024-06-01", ceoQuote: null, sourceUrl: null },
      { company: "Dropbox", logo: null, industry: "Cloud Storage", employeesCut: 500, totalEmployeesBefore: 2800, percentageCut: 18, trigger: "AI restructuring", layoffType: "2026", stockImpact: "positive", description: "Dropbox cut 18% of staff, pivoting from cloud storage to AI-powered knowledge work tools.", date: "2023-04-27", ceoQuote: null, sourceUrl: null },
      { company: "HubSpot", logo: null, industry: "CRM / Marketing", employeesCut: 500, totalEmployeesBefore: 7400, percentageCut: 7, trigger: "Efficiency restructuring", layoffType: "2022", stockImpact: "neutral", description: "HubSpot cut roles to improve margins while investing in AI marketing automation.", date: "2024-01-11", ceoQuote: null, sourceUrl: null },
      { company: "Atlassian", logo: null, industry: "Dev Tools / SaaS", employeesCut: 500, totalEmployeesBefore: 11000, percentageCut: 5, trigger: "Cloud transition + AI pivot", layoffType: "2026", stockImpact: "neutral", description: "Atlassian restructured teams around AI-first products and sunset some legacy lines.", date: "2024-02-01", ceoQuote: null, sourceUrl: null },
      { company: "Workday", logo: null, industry: "Enterprise HR SaaS", employeesCut: 500, totalEmployeesBefore: 18000, percentageCut: 3, trigger: "AI efficiency", layoffType: "2026", stockImpact: "positive", description: "Workday trimmed roles and shifted investment toward AI agents for HR workflows.", date: "2025-02-01", ceoQuote: null, sourceUrl: null },
      { company: "Zillow", logo: null, industry: "Real Estate Tech", employeesCut: 2000, totalEmployeesBefore: 8000, percentageCut: 25, trigger: "iBuying failure", layoffType: "2008", stockImpact: "negative", description: "Zillow shut down its iBuying program and laid off 25% of staff after massive losses on home flipping.", date: "2021-11-02", ceoQuote: null, sourceUrl: null },
      { company: "Peloton", logo: null, industry: "Fitness / Hardware", employeesCut: 2800, totalEmployeesBefore: 8600, percentageCut: 33, trigger: "Post-pandemic demand crash", layoffType: "2008", stockImpact: "negative", description: "Peloton slashed a third of its workforce as pandemic fitness demand cratered.", date: "2022-02-08", ceoQuote: null, sourceUrl: null },
      { company: "DoorDash", logo: null, industry: "Food Delivery", employeesCut: 1250, totalEmployeesBefore: 19000, percentageCut: 6, trigger: "Over-hiring correction", layoffType: "2022", stockImpact: "neutral", description: "DoorDash acknowledged over-hiring during pandemic delivery boom and reduced headcount.", date: "2022-11-30", ceoQuote: null, sourceUrl: null },
      { company: "Netflix", logo: null, industry: "Streaming", employeesCut: 450, totalEmployeesBefore: 11300, percentageCut: 4, trigger: "Subscriber slowdown", layoffType: "2022", stockImpact: "negative", description: "Netflix cut staff across content and recruiting as subscriber growth stalled for the first time.", date: "2022-06-23", ceoQuote: null, sourceUrl: null },
      { company: "Pinterest", logo: null, industry: "Social Media / E-Commerce", employeesCut: 150, totalEmployeesBefore: 3900, percentageCut: 4, trigger: "Efficiency restructuring", layoffType: "2022", stockImpact: "neutral", description: "Pinterest cut roles to streamline operations under new leadership.", date: "2023-02-01", ceoQuote: null, sourceUrl: null },
      { company: "Carvana", logo: null, industry: "Auto / E-Commerce", employeesCut: 2500, totalEmployeesBefore: 15000, percentageCut: 17, trigger: "Financial crisis", layoffType: "2008", stockImpact: "negative", description: "Carvana slashed headcount as used car market collapsed and debt levels became unsustainable.", date: "2022-05-10", ceoQuote: null, sourceUrl: null },
      { company: "Redfin", logo: null, industry: "Real Estate Tech", employeesCut: 900, totalEmployeesBefore: 6000, percentageCut: 15, trigger: "Housing market slowdown", layoffType: "2008", stockImpact: "negative", description: "Redfin cut agents and staff as rising interest rates froze the housing market.", date: "2022-11-09", ceoQuote: null, sourceUrl: null },
      { company: "Opendoor", logo: null, industry: "Real Estate Tech", employeesCut: 560, totalEmployeesBefore: 3100, percentageCut: 18, trigger: "Housing downturn", layoffType: "2008", stockImpact: "negative", description: "Opendoor cut staff as iBuying losses mounted amid falling home prices.", date: "2022-11-03", ceoQuote: null, sourceUrl: null },
      { company: "Compass Inc.", logo: null, industry: "Real Estate Tech", employeesCut: 800, totalEmployeesBefore: 5000, percentageCut: 16, trigger: "Housing market slowdown", layoffType: "2008", stockImpact: "negative", description: "Compass reduced headcount as housing transactions plummeted.", date: "2022-06-15", ceoQuote: null, sourceUrl: null },
      { company: "Loom", logo: null, industry: "Video Communications", employeesCut: 100, totalEmployeesBefore: 400, percentageCut: 25, trigger: "Post-acquisition restructuring", layoffType: "2022", stockImpact: null, description: "Loom cut staff after being acquired by Atlassian and integrating into the broader platform.", date: "2024-02-15", ceoQuote: null, sourceUrl: null },
      { company: "Wix", logo: null, industry: "Website Builder", employeesCut: 400, totalEmployeesBefore: 5500, percentageCut: 7, trigger: "AI pivot + efficiency", layoffType: "2026", stockImpact: "neutral", description: "Wix cut roles while shifting to AI-powered website generation capabilities.", date: "2023-03-01", ceoQuote: null, sourceUrl: null },
      { company: "Squarespace", logo: null, industry: "Website Builder", employeesCut: 150, totalEmployeesBefore: 1800, percentageCut: 8, trigger: "Going-private restructuring", layoffType: "2022", stockImpact: null, description: "Squarespace reduced staff as part of going-private transition and operational streamlining.", date: "2024-05-01", ceoQuote: null, sourceUrl: null },
      { company: "SoundCloud", logo: null, industry: "Audio Streaming", employeesCut: 200, totalEmployeesBefore: 800, percentageCut: 25, trigger: "Revenue pressure", layoffType: "2008", stockImpact: null, description: "SoundCloud cut a quarter of staff amid ongoing profitability challenges.", date: "2023-08-07", ceoQuote: null, sourceUrl: null },
      { company: "Vimeo", logo: null, industry: "Video Platform", employeesCut: 130, totalEmployeesBefore: 1200, percentageCut: 11, trigger: "Profitability restructuring", layoffType: "2022", stockImpact: "neutral", description: "Vimeo cut staff after spinning off from IAC and focusing on enterprise video.", date: "2023-01-04", ceoQuote: null, sourceUrl: null },
      { company: "GitHub", logo: null, industry: "Dev Tools", employeesCut: 300, totalEmployeesBefore: 3000, percentageCut: 10, trigger: "AI Copilot restructuring", layoffType: "2026", stockImpact: null, description: "GitHub restructured teams around Copilot AI, reducing roles in areas now handled by AI-assisted development.", date: "2024-02-01", ceoQuote: null, sourceUrl: null },
      { company: "GitLab", logo: null, industry: "Dev Tools / CI-CD", employeesCut: 114, totalEmployeesBefore: 2000, percentageCut: 7, trigger: "Efficiency restructuring", layoffType: "2022", stockImpact: "neutral", description: "GitLab trimmed roles to improve operational efficiency and path to profitability.", date: "2023-02-09", ceoQuote: null, sourceUrl: null },
      { company: "Flexport", logo: null, industry: "Logistics / Supply Chain", employeesCut: 600, totalEmployeesBefore: 3400, percentageCut: 18, trigger: "Leadership change + restructuring", layoffType: "2022", stockImpact: null, description: "Flexport cut 18% after founder returned as CEO and reversed the previous expansion strategy.", date: "2023-10-13", ceoQuote: null, sourceUrl: null },
      { company: "Convoy", logo: null, industry: "Logistics / Trucking", employeesCut: 500, totalEmployeesBefore: 500, percentageCut: 100, trigger: "Company shutdown", layoffType: "2008", stockImpact: null, description: "Convoy shut down entirely as freight market conditions made the business model unviable.", date: "2023-10-18", ceoQuote: null, sourceUrl: null },
      { company: "Olive AI", logo: null, industry: "Health Tech / AI", employeesCut: 450, totalEmployeesBefore: 800, percentageCut: 56, trigger: "Pivot failure + shutdown", layoffType: "2008", stockImpact: null, description: "Olive AI wound down operations after its healthcare AI automation strategy failed to achieve scale.", date: "2023-10-31", ceoQuote: null, sourceUrl: null },
      { company: "Noom", logo: null, industry: "Health Tech", employeesCut: 500, totalEmployeesBefore: 3700, percentageCut: 14, trigger: "Revenue slowdown", layoffType: "2022", stockImpact: null, description: "Noom cut 14% of staff as health and wellness subscription growth plateaued.", date: "2023-02-08", ceoQuote: null, sourceUrl: null },
      { company: "WeWork", logo: null, industry: "Real Estate / Co-working", employeesCut: 3400, totalEmployeesBefore: 5100, percentageCut: 67, trigger: "Bankruptcy restructuring", layoffType: "2008", stockImpact: null, description: "WeWork cut two-thirds of its workforce during bankruptcy proceedings.", date: "2023-11-06", ceoQuote: null, sourceUrl: null },
      { company: "Klarna", logo: null, industry: "Fintech / BNPL", employeesCut: 700, totalEmployeesBefore: 5000, percentageCut: 14, trigger: "AI replacement + efficiency", layoffType: "2026", stockImpact: null, description: "Klarna replaced customer service roles with AI and reduced total headcount by 14%.", date: "2024-05-01", ceoQuote: null, sourceUrl: null },
      { company: "Chewy", logo: null, industry: "E-Commerce / Pets", employeesCut: 400, totalEmployeesBefore: 14400, percentageCut: 3, trigger: "Post-pandemic normalization", layoffType: "2022", stockImpact: "neutral", description: "Chewy trimmed staff as pet supply demand returned to pre-pandemic levels.", date: "2023-06-22", ceoQuote: null, sourceUrl: null },
      { company: "Instacart", logo: null, industry: "Grocery Delivery", employeesCut: 250, totalEmployeesBefore: 3400, percentageCut: 7, trigger: "Pre-IPO restructuring", layoffType: "2022", stockImpact: null, description: "Instacart cut roles to improve financials ahead of its public offering.", date: "2023-01-23", ceoQuote: null, sourceUrl: null },
      { company: "Bumble", logo: null, industry: "Dating / Social", employeesCut: 350, totalEmployeesBefore: 1200, percentageCut: 29, trigger: "Revenue decline + restructuring", layoffType: "2022", stockImpact: "negative", description: "Bumble cut nearly a third of staff as dating app growth stalled and competition intensified.", date: "2024-02-05", ceoQuote: null, sourceUrl: null },
      { company: "Match Group", logo: null, industry: "Dating / Social", employeesCut: 300, totalEmployeesBefore: 12000, percentageCut: 2.5, trigger: "Efficiency restructuring", layoffType: "2022", stockImpact: "neutral", description: "Match Group reduced headcount across Tinder and Hinge teams to improve margins.", date: "2024-02-13", ceoQuote: null, sourceUrl: null },
      { company: "Duolingo", logo: null, industry: "EdTech / AI", employeesCut: 60, totalEmployeesBefore: 800, percentageCut: 8, trigger: "AI content generation", layoffType: "2026", stockImpact: "positive", description: "Duolingo replaced contract language content creators with AI-generated lessons.", date: "2024-01-08", ceoQuote: null, sourceUrl: null },
      { company: "Chegg", logo: null, industry: "EdTech", employeesCut: 560, totalEmployeesBefore: 1900, percentageCut: 29, trigger: "ChatGPT competition", layoffType: "2026", stockImpact: "negative", description: "Chegg's tutoring business collapsed as students switched to ChatGPT for homework help.", date: "2024-06-18", ceoQuote: null, sourceUrl: null },
      { company: "Coursera", logo: null, industry: "EdTech", employeesCut: 200, totalEmployeesBefore: 2000, percentageCut: 10, trigger: "Post-pandemic correction", layoffType: "2022", stockImpact: "negative", description: "Coursera cut staff as online education demand declined from pandemic peaks.", date: "2023-09-21", ceoQuote: null, sourceUrl: null },
      { company: "Niantic", logo: null, industry: "Gaming / AR", employeesCut: 230, totalEmployeesBefore: 800, percentageCut: 29, trigger: "Revenue decline + pivot", layoffType: "2022", stockImpact: null, description: "Pokemon Go maker Niantic cut 29% and canceled multiple AR projects.", date: "2023-06-29", ceoQuote: null, sourceUrl: null },
      { company: "Electronic Arts", logo: null, industry: "Gaming", employeesCut: 670, totalEmployeesBefore: 13000, percentageCut: 5, trigger: "Portfolio restructuring", layoffType: "2022", stockImpact: "neutral", description: "EA cut staff while canceling underperforming games and doubling down on live services.", date: "2024-02-27", ceoQuote: null, sourceUrl: null },
      { company: "Epic Games", logo: null, industry: "Gaming / Engine", employeesCut: 870, totalEmployeesBefore: 5000, percentageCut: 17, trigger: "Metaverse spending cuts", layoffType: "2022", stockImpact: null, description: "Epic cut 17% after over-investing in metaverse-related projects that didn't generate returns.", date: "2023-09-28", ceoQuote: null, sourceUrl: null },
      { company: "Riot Games", logo: null, industry: "Gaming", employeesCut: 530, totalEmployeesBefore: 4500, percentageCut: 11, trigger: "Diversification failure", layoffType: "2022", stockImpact: null, description: "Riot cut 11% after its efforts to diversify beyond League of Legends underperformed.", date: "2024-01-22", ceoQuote: null, sourceUrl: null },
      { company: "BuzzFeed", logo: null, industry: "Media / Digital", employeesCut: 330, totalEmployeesBefore: 1500, percentageCut: 22, trigger: "Digital media collapse", layoffType: "2008", stockImpact: "negative", description: "BuzzFeed shut down its news division and cut 22% of staff as digital ad revenue cratered.", date: "2023-04-20", ceoQuote: null, sourceUrl: null },
      { company: "Vice Media", logo: null, industry: "Media / Digital", employeesCut: 250, totalEmployeesBefore: 1500, percentageCut: 17, trigger: "Bankruptcy restructuring", layoffType: "2008", stockImpact: null, description: "Vice Media cut staff during bankruptcy as the digital media business model collapsed.", date: "2023-05-15", ceoQuote: null, sourceUrl: null },
      { company: "Udemy", logo: null, industry: "EdTech", employeesCut: 190, totalEmployeesBefore: 1700, percentageCut: 11, trigger: "Post-pandemic normalization", layoffType: "2022", stockImpact: "neutral", description: "Udemy reduced headcount as online learning enrollment declined from pandemic highs.", date: "2024-02-01", ceoQuote: null, sourceUrl: null },
      { company: "Expedia", logo: null, industry: "Travel Tech", employeesCut: 1500, totalEmployeesBefore: 20400, percentageCut: 7, trigger: "Efficiency restructuring", layoffType: "2022", stockImpact: "positive", description: "Expedia streamlined operations and consolidated brands under fewer teams.", date: "2024-02-22", ceoQuote: null, sourceUrl: null },
      { company: "Booking Holdings", logo: null, industry: "Travel Tech", employeesCut: 2800, totalEmployeesBefore: 21200, percentageCut: 13, trigger: "Pandemic revenue collapse", layoffType: "2008", stockImpact: "negative", description: "Booking Holdings cut 13% as international travel froze during COVID.", date: "2020-08-04", ceoQuote: null, sourceUrl: null },
      { company: "Wish", logo: null, industry: "E-Commerce", employeesCut: 340, totalEmployeesBefore: 1100, percentageCut: 31, trigger: "Revenue collapse", layoffType: "2008", stockImpact: "negative", description: "Wish cut nearly a third of staff as its discount e-commerce model lost users to Temu and Shein.", date: "2023-01-26", ceoQuote: null, sourceUrl: null },
      { company: "Groupon", logo: null, industry: "E-Commerce / Deals", employeesCut: 500, totalEmployeesBefore: 2500, percentageCut: 20, trigger: "Business model decline", layoffType: "2008", stockImpact: "negative", description: "Groupon cut 20% as the daily deals model continued to erode.", date: "2023-04-17", ceoQuote: null, sourceUrl: null },
      { company: "Oscar Health", logo: null, industry: "Health Insurance", employeesCut: 300, totalEmployeesBefore: 3000, percentageCut: 10, trigger: "Path to profitability", layoffType: "2022", stockImpact: "positive", description: "Oscar Health reduced staff while improving unit economics toward profitability.", date: "2023-03-08", ceoQuote: null, sourceUrl: null },
      { company: "Rapid7", logo: null, industry: "Cybersecurity", employeesCut: 470, totalEmployeesBefore: 3500, percentageCut: 13, trigger: "Efficiency restructuring", layoffType: "2022", stockImpact: "neutral", description: "Rapid7 cut 13% as the cybersecurity sector consolidated and growth slowed.", date: "2024-02-05", ceoQuote: null, sourceUrl: null },
      { company: "CrowdStrike", logo: null, industry: "Cybersecurity", employeesCut: 500, totalEmployeesBefore: 9500, percentageCut: 5, trigger: "Outage fallout + restructuring", layoffType: "2022", stockImpact: "negative", description: "CrowdStrike reduced staff after a major global outage damaged its reputation.", date: "2024-09-01", ceoQuote: null, sourceUrl: null },
      { company: "Twitch", logo: null, industry: "Streaming / Gaming", employeesCut: 500, totalEmployeesBefore: 2500, percentageCut: 20, trigger: "Amazon restructuring", layoffType: "2022", stockImpact: null, description: "Twitch cut 20% as Amazon restructured its streaming investment for profitability.", date: "2024-01-09", ceoQuote: null, sourceUrl: null },
      { company: "Discord", logo: null, industry: "Communications / Gaming", employeesCut: 170, totalEmployeesBefore: 1000, percentageCut: 17, trigger: "Profitability restructuring", layoffType: "2022", stockImpact: null, description: "Discord cut 17% as it shifted from growth mode to finding sustainable revenue.", date: "2024-01-11", ceoQuote: null, sourceUrl: null },
      { company: "Ring / Blink", logo: null, industry: "Smart Home / IoT", employeesCut: 600, totalEmployeesBefore: 3000, percentageCut: 20, trigger: "Amazon consolidation", layoffType: "2022", stockImpact: null, description: "Amazon's Ring and Blink divisions cut 20% as hardware unit economics were restructured.", date: "2023-10-18", ceoQuote: null, sourceUrl: null },
      { company: "Justworks", logo: null, industry: "HR / Payroll SaaS", employeesCut: 90, totalEmployeesBefore: 950, percentageCut: 9, trigger: "Growth slowdown", layoffType: "2022", stockImpact: null, description: "Justworks trimmed roles as SMB hiring slowed and customer acquisition costs rose.", date: "2023-06-01", ceoQuote: null, sourceUrl: null },
      { company: "Evernote", logo: null, industry: "Productivity / Notes", employeesCut: 129, totalEmployeesBefore: 400, percentageCut: 32, trigger: "Acquisition restructuring", layoffType: "2008", stockImpact: null, description: "Evernote gutted most of its US staff after being acquired by Bending Spoons.", date: "2023-07-05", ceoQuote: null, sourceUrl: null },
      { company: "Indeed", logo: null, industry: "Job Search", employeesCut: 2200, totalEmployeesBefore: 15000, percentageCut: 15, trigger: "Hiring slowdown", layoffType: "2022", stockImpact: null, description: "Indeed cut 15% as job postings declined and employer hiring budgets tightened.", date: "2023-03-22", ceoQuote: null, sourceUrl: null },
      { company: "Glassdoor", logo: null, industry: "Job Search / Reviews", employeesCut: 140, totalEmployeesBefore: 900, percentageCut: 16, trigger: "Hiring market decline", layoffType: "2022", stockImpact: null, description: "Glassdoor reduced staff as employer review and job posting volumes declined.", date: "2024-02-01", ceoQuote: null, sourceUrl: null },
      { company: "ZipRecruiter", logo: null, industry: "Job Search", employeesCut: 270, totalEmployeesBefore: 1800, percentageCut: 15, trigger: "Hiring market slowdown", layoffType: "2022", stockImpact: "negative", description: "ZipRecruiter cut roles as job posting demand fell across all sectors.", date: "2023-10-03", ceoQuote: null, sourceUrl: null },
    ];

    for (const entry of entries) {
      const id = randomUUID();
      this.layoffs.set(id, { ...entry, id });
    }
  }

  async getLayoffs(): Promise<Layoff[]> {
    return Array.from(this.layoffs.values()).sort(
      (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
    );
  }

  async getLayoff(id: string): Promise<Layoff | undefined> {
    return this.layoffs.get(id);
  }

  async createLayoff(insertLayoff: InsertLayoff): Promise<Layoff> {
    const id = randomUUID();
    const layoff: Layoff = { ...insertLayoff, id };
    this.layoffs.set(id, layoff);
    return layoff;
  }

  async getUser(id: string): Promise<User | undefined> {
    return this.users.get(id);
  }

  async getUserByUsername(username: string): Promise<User | undefined> {
    return Array.from(this.users.values()).find((u) => u.username === username);
  }

  async createUser(insertUser: InsertUser): Promise<User> {
    const id = randomUUID();
    const user: User = { ...insertUser, id };
    this.users.set(id, user);
    return user;
  }
}

export const storage = new MemStorage();
